---
title: "generate_data"
author: "Peter Lin"
date: '2018-03-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dependencies}
library(tidyverse)
```


## sampling for toy data set


```{r sampling patient-side data}
set.seed(123)
clinic_id <- c(1:10)
clinic_name <- sample(x = c("Kootenay Loop Opt Clinic", 
                            "South Hill Opt Clinic", 
                            "Vancouver Opt Clinic", 
                            "ADAP", 
                            "AIDS Vancouver", 
                            "Alina Wydra",
                            "Aquarius Medical Clinic",
                            "Bayswater Medical Clinic",
                            "Bloom Community Midwives",
                            "BLUSH"), size = 500, replace = TRUE, 
                      prob = c(0.05, 0.01, 0.01, 0.3, 0.01, 0.05, 0.1, 0.01, 0.2, 0.1))
clinic_open <- sample(x = c(8,9,10), size = 500, replace = TRUE, 
                      prob = c(0.05, 0.8, 0.1))
clinic_close <- sample(x = c(3,4,5), size = 500, replace = TRUE, 
                      prob = c(0.1, 0.5, 0.3))

clinic_location <- rep("VAN", 500)
msp_required <- rbinom(n = 500, size = 1, prob = c(0.9,0.2,0.3))
year <- sample(x=c(2013, 2014, 2015, 2016, 2017), size=500, replace = TRUE) 
age <- sample(x=c(14:70), size=500, replace = TRUE) 

gender <- sample(x = c("female", "male", "unspecified"), size=500, replace = TRUE, prob = c(0.1, 0.4, 0.2)) 



sexual_orientaton <- sample(x = c(1:7), size=500, replace = TRUE, prob = c(0.1, 0.4, 0.2, 0.1, 0.1, 0.4, 0.1))

service_type <- sample(x = c("sti_testing", "pregnancy_testing", "counselling", "birth control services", "abortion", "emergency contraceptive"), size = 500, replace = TRUE, prob = c(0.1, 0.2, 0.1, 0.1, 0.05, 0.1))

user_feedback_tags1 <- sample(x = c("clean", "messy"), size = 500, replace = TRUE, prob = c(0.45, 0.2))
user_feedback_tags2 <- sample(x = c("uncomfortable", "nonjudgemental"), size = 500, replace = TRUE, prob = c(0.3, 0.4))
user_feedback_tags3 <- sample(x = c("friendly", "safe"), size = 500, replace = TRUE, prob = c(0.25, 0.3))
user_feedback_tags4 <- sample(x = c("fast", "longwaittimes"), size = 500, replace = TRUE, prob = c(0.1, 0.7))
user_feedback_tags5 <- sample(x = c("professional", "empathy"), size = 500, replace = TRUE)
```

```{r join into dataframe}
patient_side_data <- data.frame(clinic_id, 
                                clinic_name,
                                clinic_location,
                                clinic_open,
                                clinic_close,
                                msp_required,
                                year,
                                age,
                                gender,
                                sexual_orientaton,
                                service_type,
                                user_feedback_tags1,
                                user_feedback_tags2,
                                user_feedback_tags3,
                                user_feedback_tags4,
                                user_feedback_tags5)
```

```{r clean up male-abortion}

patient_side_data$service_type[patient_side_data$gender == "male"] <- sample(x = c("sti_testing", "counselling"), size = 1)
  

```


```{r export to csv}
write.csv(x=patient_side_data, file = "patient_side_data.csv")
```

