---
title: "generate_data"
author: "Peter Lin"
date: '2018-03-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dependencies}
library(tidyverse)
```


## sampling for toy data set


```{r sampling patient-side data}
set.seed(123)

clinic_id <- 1

clinic_name <- sample(x = c("Kootenay Loop Opt Clinic", 
                            "South Hill Opt Clinic", 
                            "Vancouver Opt Clinic", 
                            "ADAP", 
                            "AIDS Vancouver", 
                            "Alina Wydra",
                            "Aquarius Medical Clinic",
                            "Bayswater Medical Clinic",
                            "Bloom Community Midwives",
                            "BLUSH"), size = 500, replace = TRUE, 
                      prob = c(0.05, 0.01, 0.01, 0.3, 0.01, 0.05, 0.1, 0.01, 0.2, 0.1))
clinic_open <- sample(x = c(8,9,10), size = 500, replace = TRUE, 
                      prob = c(0.05, 0.8, 0.1))
clinic_close <- sample(x = c(3,4,5), size = 500, replace = TRUE, 
                      prob = c(0.1, 0.5, 0.3))

clinic_location <- rep("VAN", 500)
msp_required <- rbinom(n = 500, size = 1, prob = c(0.9,0.2,0.3))
year <- sample(x=c(2013, 2014, 2015, 2016, 2017), size=500, replace = TRUE) 
age <- sample(x=c(14:70), size=500, replace = TRUE) 

gender <- sample(x = c("female", "male", "unspecified"), size=500, replace = TRUE, prob = c(0.1, 0.4, 0.2)) 



sexual_orientaton <- sample(x = c(1:7), size=500, replace = TRUE, prob = c(0.1, 0.4, 0.2, 0.1, 0.1, 0.4, 0.1))

service_type <- sample(x = c("sti_testing", "pregnancy_testing", "counselling", "birth_control_services", "abortion", "emergency_contraceptive"), size = 500, replace = TRUE, prob = c(0.1, 0.2, 0.1, 0.1, 0.05, 0.1))


user_feedback_tags1 <- sample(x = c("clean", "messy"), size = 500, replace = TRUE, prob = c(0.45, 0.2))
user_feedback_tags2 <- sample(x = c("uncomfortable", "nonjudgemental"), size = 500, replace = TRUE, prob = c(0.3, 0.4))
user_feedback_tags3 <- sample(x = c("friendly", "safe"), size = 500, replace = TRUE, prob = c(0.25, 0.3))
user_feedback_tags4 <- sample(x = c("fast", "longwaittimes"), size = 500, replace = TRUE, prob = c(0.1, 0.7))
user_feedback_tags5 <- sample(x = c("professional", "empathy"), size = 500, replace = TRUE)
```

```{r join into dataframe}
patient_side_data <- data.frame(clinic_id, 
                                clinic_name,
                                clinic_location,
                                clinic_open,
                                clinic_close,
                                msp_required,
                                year,
                                age,
                                gender,
                                sexual_orientaton,
                                service_type,
                                user_feedback_tags1,
                                user_feedback_tags2,
                                user_feedback_tags3,
                                user_feedback_tags4,
                                user_feedback_tags5)
```

```{r clean up male-abortion and clinic ID}

patient_side_data$service_type[patient_side_data$gender == "male"] <- sample(x = c("sti_testing", "counselling"), size = 1)
  
#"Kootenay Loop Opt Clinic", "South Hill Opt Clinic", "Vancouver Opt Clinic", "ADAP", "AIDS Vancouver", "Alina Wydra", "Aquarius Medical Clinic","Bayswater Medical Clinic", "Bloom Community Midwives", "BLUSH"

patient_side_data$clinic_id[patient_side_data$clinic_name == "Kootenay Loop Opt Clinic"] <- 1
patient_side_data$clinic_id[patient_side_data$clinic_name == "South Hill Opt Clinic"] <- 2
patient_side_data$clinic_id[patient_side_data$clinic_name == "Vancouver Opt Clinic"] <- 3
patient_side_data$clinic_id[patient_side_data$clinic_name == "ADAP"] <- 4
patient_side_data$clinic_id[patient_side_data$clinic_name == "AIDS Vancouver"] <- 5
patient_side_data$clinic_id[patient_side_data$clinic_name == "Alina Wydra"] <- 6
patient_side_data$clinic_id[patient_side_data$clinic_name == "Aquarius Medical Clinic"] <- 7
patient_side_data$clinic_id[patient_side_data$clinic_name == "Bayswater Medical Clinic"] <- 8
patient_side_data$clinic_id[patient_side_data$clinic_name == "Bloom Community Midwives"] <- 9
patient_side_data$clinic_id[patient_side_data$clinic_name == "BLUSH"] <- 10

```


```{r export to csv}
write.csv(x=patient_side_data, file = "patient_side_data.csv")
```


```{r inspect csv}
finished_df <- data.frame(read_csv("patient_side_data.csv"))
head(finished_df)
```


```{r simple viz1}
ggplot(patient_side_data, aes(x=age, fill=user_feedback_tags1)) +
  geom_bar() +
  facet_wrap(~user_feedback_tags1) +
  ggtitle("Feedback 'clean vs messy' by age" )
```

```{r simple viz2}
ggplot(patient_side_data, aes(x=gender, fill=user_feedback_tags1)) +
  geom_bar() +
  facet_wrap(~user_feedback_tags1) +
  ggtitle("Feedback 'clean vs messy' by gender" )
```

```{r simple viz3}
ggplot(patient_side_data, aes(x=clinic_name, fill=user_feedback_tags1)) +
  geom_bar() +
  facet_wrap(~user_feedback_tags1) +
  ggtitle("Feedback 'clean vs messy' by clinic_name" ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r simple viz4}
ggplot(patient_side_data, aes(x=age, fill=user_feedback_tags1)) +
  geom_bar() +
  ggtitle("Feedback 'clean vs messy' by clinic_name" ) +
  facet_wrap(~clinic_name)

```

```{r simple viz5}
ggplot(patient_side_data, aes(x=year, fill=user_feedback_tags1)) +
  geom_bar() +
  ggtitle("Feedback 'clean vs messy' by year" ) +
  facet_wrap(~clinic_name) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



```{r simple viz6}
ggplot(patient_side_data, aes(x=service_type, fill=user_feedback_tags1)) +
  geom_bar() +
  ggtitle("Service Type" ) +
  facet_wrap(~user_feedback_tags1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



